### ISSUE TITLE
 module 'mlx.core' has no attribute 'simplify'

### ISSUE THREAD

**Issue by madjuju** [neobundy/MLX-Stable-Diffusion-WebUI#2]
Traceback (most recent call last):
  File "/Users/julien/miniconda3/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/Users/julien/temp/MLX-Stable-Diffusion-WebUI/main.py", line 114, in <module>
    mx.simplify(x_t)
    ^^^^^^^^^^^
AttributeError: module 'mlx.core' has no attribute 'simplify'

**Comment by neobundy** [comment]
The MLX team removed 'simplify' in the latest version of MLX. I did the same in `main.py`.  It should work as expected now.

**Comment by madjuju** [comment]
Nice
